[package]
name = "merkle-variants"
description = "Binary, sparse, and Patricia Merkle tree implementations for MerkleForge Framework"
readme = "README.md"
version.workspace    = true
edition.workspace    = true
rust-version.workspace = true
authors.workspace    = true
license.workspace    = true
repository.workspace = true
homepage.workspace   = true
documentation = "https://docs.rs/merkle-variants"
keywords.workspace   = true

[dependencies]
merkle-core = { workspace = true }
serde       = { workspace = true }
tiny-keccak = { workspace = true }

[dev-dependencies]
merkleforge-hash = { workspace = true }
proptest         = { workspace = true }
serde_json       = { workspace = true }
